# Generated by Django 5.0.7 on 2024-07-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.PositiveSmallIntegerField(verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_date', models.DateTimeField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id', 'release_date'],
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.contact', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('debt', models.PositiveIntegerField(default=0, verbose_name='Задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.contact', verbose_name='Контакты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prod_net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.network', verbose_name='Сеть')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.factory', verbose_name='Фабрика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('supplier_choice', models.CharField(choices=[('1', 'FACTORY'), ('2', 'NETWORK')], default='2', verbose_name='Поставщик')),
                ('debt', models.PositiveIntegerField(default=0, verbose_name='Задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.contact', verbose_name='Контакты')),
                ('supplier_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics.factory', verbose_name='Поставщик')),
                ('supplier_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics.network', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Предпрениматель',
                'verbose_name_plural': 'Предпрениматели',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prod_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.product', verbose_name='Продукт')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.seller', verbose_name='Предпрениматель')),
            ],
        ),
    ]
