# Generated by Django 5.0.7 on 2024-07-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='supplier_choice',
            field=models.CharField(choices=[('1', 'Фабрика'), ('2', 'Розничная сеть')], default='2', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='supplier_factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics.factory', verbose_name='Поставщик (фабрика)'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='supplier_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics.network', verbose_name='Поставщик (розничная сеть)'),
        ),
    ]
